language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_install:
 - sudo apt-get install cutycapt
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
notifications:
 irc:
   - "irc.freenode.org#mdvlrb"